principal: antlr4 CsvLexer.g4;antlr4 CsvParser.g4;javac *.java

.PHONY: clean clean_java clean_class clean_interp clean_tokens
java:
	rm -f *.java

class:
	rm -rf *.class

interp:
	rm -rf *.interp

tokens:
	rm -rf *.java

clean:
	rm -f *.java *.class *.interp *.tokens
